#!/bin/bash

#PBS -S /bin/bash
#PBS -o pbs_out.dat
#PBS -j oe
#PBS -l nodes=1:ppn=40
#PBS -M reamerb1@wit.edu
#PBS -m be
cd $PBS_O_WORKDIR
for i in {1..50}; do
    echo -e "i=$i\t$(mpirun -np $i -machinefile $PBS_NODEFILE ./tsp)" >> output_torque.txt;
done